KPax/Models/GitSetupViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using KPax.DataModels;

namespace KPax.Models
{
    public class GitSetupViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Local repository path")]
        public string RepositoryPath { get; set; }

        [Required]
        [Display(Name = "Project")]
        public Project Project { get; set; }

        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

KPax/Controllers/GitSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KPax.DataModels;
using KPax.Models;
using KPax.Util;

namespace KPax.Controllers
{
    public class GitSetupController : Controller
    {
        private EntitiesDB db = new EntitiesDB();

        // GET: GitSetup
        public ActionResult Index()
        {
            int count = db.ProjectUser.Count(i => i.UserName == User.Identity.Name);
            if (count == 0)
            {
                return RedirectToAction("../Projects");
            }

            var listModel = db.GitSetup.ToList();
            var viewList = new List<GitSetupViewModel>();
            var projects = db.ProjectUser.Where(pu => pu.UserName.Trim() == User.Identity.Name).Select(pu => pu.Project);
            foreach (var model in listModel)
            {
                var viewModel = new GitSetupViewModel()
                {
                    Id = model.Id,
                    RepositoryPath = model.RepositoryPath,
                    Project = projects.FirstOrDefault(m => m.Id == model.ProjectId),
                    Description = model.Description
                };
                viewList.Add(viewModel);
            }
            //new GitSharpClient().OpenRepo();
            return View(viewList);
        }

        // GET: GitSetup/Details/5
        public ActionResult Details(int id)
        {
            var model = db.GitSetup.FirstOrDefault(i => i.Id == id);
            var gitSharpClient =new GitSharpClient(model.RepositoryPath);

            ViewBag.CurrentBranch = gitSharpClient.CurrentBranch().FriendlyName;
            ViewBag.LastTag = gitSharpClient.LastTag();
            ViewBag.LastModify = gitSharpClient.LastModify();
            ViewBag.Status = gitSharpClient.Status();
            
            return Edit(id);
        }

        public ActionResult Pull(int id)
        {
            try
            {
                var model = db.GitSetup.FirstOrDefault(i => i.Id == id);
                string credential = new Crypt32().Decrypt(model.Crendential);
                var status = new GitSharpClient(model.RepositoryPath).Pull(credential.Split('|')[0], credential.Split('|')[1]);
                TempData["Success"] = "Git pull command process with success. " + status;
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = e.Message;
            }

            return Redirect(Request.UrlReferrer.PathAndQuery);
        }

        // GET: GitSetup/Create
        public ActionResult Create()
        {
            var projects = db.ProjectUser.Where(pu => pu.UserName.Trim() == User.Identity.Name).Select(pu => pu.Project);
            ViewBag.ProjectsList = new SelectList(projects.ToList(), "Id", "Name");
            return View();
        }

        // POST: GitSetup/Create
        [HttpPost]
        public ActionResult Create(GitSetupViewModel viewModel, string returnUrl)
        {
            var projects = db.ProjectUser.Where(pu => pu.UserName.Trim() == User.Identity.Name).Select(pu => pu.Project);
            ViewBag.ProjectsList = new SelectList(projects.ToList(), "Id", "Name");

            if (ModelState.IsValid)
            {
                try
                {
                    //if (CheckGitSetup(viewModel))
                    //{
                        // Save Data 
                        var gitModel = new GitSetup()
                        {
                            RepositoryPath = viewModel.RepositoryPath.Trim(),
                            ProjectId = viewModel.Project.Id,
                            Crendential = new Crypt32().Encrypt(Crypt32.KeyType.UserKey, viewModel.UserName + "|" + viewModel.Password),
                            Description = viewModel.Description
                        };
                        db.GitSetup.Add(gitModel);

                        db.SaveChanges();

                        return RedirectToAction("Index");
                    //}
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);
                }

            }

            return View();
        }

        // GET: GitSetup/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var projects = db.ProjectUser.Where(pu => pu.UserName.Trim() == User.Identity.Name).Select(pu => pu.Project);
                ViewBag.ProjectsList = new SelectList(projects.ToList(), "Id", "Name");

                var gitModel = db.GitSetup.Find(id);
                if (gitModel != null)
                {

                    var gitView = new GitSetupViewModel()
                    {
                        Id = gitModel.Id,
                        RepositoryPath = gitModel.RepositoryPath.Trim(),
                        Project = db.Project.FirstOrDefault(m => m.Id == gitModel.ProjectId),
                        UserName = new Crypt32().Decrypt(gitModel.Crendential).Split('|')[0],
                        Description = gitModel.Description
                    };
                    return View(gitView);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }
            return View();
        }

        // POST: GitSetup/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, GitSetupViewModel viewModel)
        {
            try
            {
                var projects = db.ProjectUser.Where(pu => pu.UserName.Trim() == User.Identity.Name).Select(pu => pu.Project);
                ViewBag.ProjectsList = new SelectList(projects.ToList(), "Id", "Name");

                //if (CheckGitSetup(viewModel))
                //{
                    var gitModel = db.GitSetup.Find(id);
                    if (gitModel != null)
                    {
                        gitModel.RepositoryPath = viewModel.RepositoryPath.Trim();
                        gitModel.ProjectId = viewModel.Project.Id;
                        gitModel.Crendential =
                            new Crypt32().Encrypt(Crypt32.KeyType.UserKey,
                                viewModel.UserName + "|" + viewModel.Password);
                        gitModel.Description = viewModel.Description;
                        db.SaveChanges();
                    }

                    return RedirectToAction("Index");
                //}
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }
            return View();
        }

        // GET: GitSetup/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                db.GitSetup.Remove(db.GitSetup.Find(id));
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }
            return View();
        }
    }
}

KPax/Views/GitSetup/Create.cshtml
@model KPax.Models.GitSetupViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Git setup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Project, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Project.Id, ViewBag.ProjectsList as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Project.Id)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.RepositoryPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RepositoryPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RepositoryPath, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control", style = "width: 580px; height: 200px" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KPax/Views/GitSetup/Details.cshtml
@model KPax.Models.GitSetupViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Git setup</h4>
    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-error">
            <p><strong>Error:</strong> @TempData["ErrorMessage"].ToString()</p>
        </div>
    }
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success">
            <p><strong>Success:</strong> @TempData["Success"].ToString()</p>
        </div>
    }
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RepositoryPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RepositoryPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        
        <dt>Description </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        
        <dt>Current branch</dt>
        <dd>
            @ViewBag.CurrentBranch
        </dd>
        
        <dt>Last tag </dt>
        <dd>
            @ViewBag.LastTag
        </dd>
        
        <dt>Last modify </dt>
        <dd>
            @ViewBag.LastModify
        </dd>
        <dt>Status </dt>
        <dd>
            @ViewBag.Status
        </dd>

        <dd>
            <input type="button" value="Pull request" class="btn btn-default" onclick="location.href='@Url.Action("Pull", "GitSetup", new { id = Model.Id })'" />        
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KPax/Views/GitSetup/Edit.cshtml
@model KPax.Models.GitSetupViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Git Setup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        
        <div class="form-group">
            @Html.LabelFor(m => m.Project, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Project.Id, ViewBag.ProjectsList as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Project.Id)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.RepositoryPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RepositoryPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RepositoryPath, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control", style = "width: 580px; height: 200px" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KPax/Views/GitSetup/Index.cshtml
@model IEnumerable<KPax.Models.GitSetupViewModel>

@{
    ViewBag.Title = "Git setup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RepositoryPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Project)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RepositoryPath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Project.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id },
            new { onclick = "return confirm('Are you sure you wish to delete this Setup?');" })
        </td>
    </tr>
}

</table>