KPax/Controllers/TeamCitySetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KPax.DataModels;
using KPax.Util;
using KPax.Models;
using System.Threading.Tasks;

namespace KPax.Controllers
{
    public class TeamCitySetupController : Controller
    {
        private EntitiesDB db = new EntitiesDB();

        public ActionResult Index()
        {
            int count = db.ProjectUser.Count(i => i.UserName == User.Identity.Name);
            if (count == 0)
            {
                return RedirectToAction("../Projects");
            }

            var listModel = db.TeamCitySetup.ToList();
            var viewList = new List<TeamCityViewModel>();

            var projects = db.ProjectUser.Where(pu => pu.UserName.Trim() == User.Identity.Name).Select(pu => pu.Project);

            foreach (var model in listModel)
            {
                var viewModel = new TeamCityViewModel()
                {
                    Id = model.Id,
                    URI = model.Uri.Trim(),
                    Project = projects.FirstOrDefault(m => m.Id == model.IdProject),
                    BuildId = model.BuildId
                };
                viewList.Add(viewModel);
            }
            return View(viewList);
        }

        public ActionResult Create()
        {
            var teamCityViewModel = new TeamCityViewModel();

            var projects = db.ProjectUser.Where(pu => pu.UserName.Trim() == User.Identity.Name).Select(pu => pu.Project);
            teamCityViewModel.ProjectList = new SelectList(projects.ToList(), "Id", "Name");

            var list = new List<string>();
            list.Add("TaggedForms_Automatedtests");
            list.Add("TaggedForms_BuildAndUnitTests");
            teamCityViewModel.BuildIdsList = new SelectList(list);

            return View(teamCityViewModel);
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "UpdateBuildIdsList")]
        public ActionResult UpdateBuildIdsList(TeamCityViewModel teamCityViewModel)
        {
            PreparToEdit(teamCityViewModel);

            if (teamCityViewModel.Id > 0)
            {
                return View("edit", teamCityViewModel);
            }

            return View("create", teamCityViewModel);    
        }

        private void PreparToEdit(TeamCityViewModel teamCityViewModel)
        {
            var projects = db.ProjectUser.Where(pu => pu.UserName.Trim() == User.Identity.Name).Select(pu => pu.Project);
            teamCityViewModel.ProjectList = new SelectList(projects, "Id", "Name");
            teamCityViewModel.BuildIdsList = new SelectList(new List<string>());
            try
            {
                var list = BaselineUtil.GetBuildIds(teamCityViewModel);
                teamCityViewModel.BuildIdsList = new SelectList(list);
            }
            catch (Exception ex)
            {
                TempData.Add("UpdateBuildIdsListException", ex.Message);
            }
        }

        // POST: TeamCitySetup/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultipleButton(Name = "action", Argument = "Create")]
        public async Task<ActionResult> Create(TeamCityViewModel viewModel, string returnUrl)
        {
            var projects = db.ProjectUser.Where(pu => pu.UserName.Trim() == User.Identity.Name).Select(pu => pu.Project);
            viewModel.ProjectList = new SelectList(projects.ToList(), "Id", "Name");
            viewModel.BuildIdsList = new SelectList(new List<string>());

            if (ModelState.IsValid)
            {
                try
                {
                    if (CheckTeamCitySetup(viewModel))
                    {
                        // Save Data 
                        var teamCityModel = new TeamCitySetup()
                        {
                            Uri = viewModel.URI.Trim(),
                            Crendential = new Crypt32().Encrypt(Crypt32.KeyType.UserKey, viewModel.UserName + ";" + viewModel.Password),
                            IdProject = viewModel.Project.Id,
                            BuildId = viewModel.BuildId
                        };
                        db.TeamCitySetup.Add(teamCityModel);

                        db.SaveChanges();

                        TempData["Success"] = "Yes";
                        return RedirectToAction("Index");
                    }
                }
                catch (WebException e)
                {
                    if (e.Response != null)
                    {
                        using (WebResponse response = e.Response)
                        {
                            var httpResponse = (HttpWebResponse) response;
                            if (httpResponse.StatusCode == HttpStatusCode.Unauthorized)
                            {
                                ModelState.AddModelError(string.Empty, "Invalid username or password.");
                            }
                            else
                            {
                                ModelState.AddModelError(string.Empty, "Cannot establish connection with this server.");
                            }
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Cannot establish connection with this server.");
                    }
                    
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);
                }

            }

            return View(viewModel);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                db.TeamCitySetup.Remove(db.TeamCitySetup.Find(id));
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }
            return View();
        }

        // GET: TeamCity/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var projects = db.ProjectUser.Where(pu => pu.UserName.Trim() == User.Identity.Name).Select(pu => pu.Project);
                var dbTeamCity = db.TeamCitySetup.Find(id);
                if (dbTeamCity != null)
                {
                    var teamCityView = new TeamCityViewModel()
                    {
                        Id = dbTeamCity.Id,
                        URI = dbTeamCity.Uri.Trim(),
                        Project = projects.FirstOrDefault(m => m.Id == dbTeamCity.IdProject),
                        BuildId = dbTeamCity.BuildId,
                        UserName = new Crypt32().Decrypt(dbTeamCity.Crendential).Split(';')[0],
                        Password = new Crypt32().Decrypt(dbTeamCity.Crendential).Split(';')[1]
                    };
                    PreparToEdit(teamCityView);
                    teamCityView.BuildId = dbTeamCity.BuildId;
                    return View(teamCityView);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }
            return View();
        }

        // POST: TeamCity/Edit/5
        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Edit")]
        public ActionResult Edit(int id, TeamCityViewModel viewModel)
        {
            try
            {
                var projects = db.ProjectUser.Where(pu => pu.UserName.Trim() == User.Identity.Name).Select(pu => pu.Project);
                ViewBag.ProjectsList = new SelectList(projects.ToList(), "Id", "Name");

                if (CheckTeamCitySetup(viewModel))
                {
                    var dbTeamCity = db.TeamCitySetup.Find(id);
                    if (dbTeamCity != null)
                    {
                        dbTeamCity.Uri = viewModel.URI.Trim();
                        dbTeamCity.Crendential =
                            new Crypt32().Encrypt(Crypt32.KeyType.UserKey,
                                viewModel.UserName + ";" + viewModel.Password);
                        dbTeamCity.IdProject = viewModel.Project.Id;
                        dbTeamCity.BuildId = viewModel.BuildId;
                        db.SaveChanges();
                    }

                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                PreparToEdit(viewModel);
                ModelState.AddModelError(string.Empty, e.Message);
            }
            return View(viewModel);
        }

        private bool CheckTeamCitySetup(TeamCityViewModel viewModel)
        {
            WebRequest request = WebRequest.Create(viewModel.URI + "/httpAuth/app/rest/latest/");
                    String encoded =
                        System.Convert.ToBase64String(
                            System.Text.Encoding.GetEncoding("ISO-8859-1")
                                .GetBytes(viewModel.UserName + ":" + viewModel.Password));
                    request.Headers.Add("Authorization", "Basic " + encoded);

            using (WebResponse response = request.GetResponse())
            {
                return (((HttpWebResponse) response).StatusCode == HttpStatusCode.OK);
            }
        }
    }
}

KPax/Views/TeamCitySetup/Create.cshtml
@model KPax.Models.TeamCityViewModel

@{
    ViewBag.Title = "Create new";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TeamCity setup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Project, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Project.Id, Model.ProjectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Project.Id)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.URI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.BuildId, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.BuildId, Model.BuildIdsList, "Select..", new { @class = "form-control" })
                <input type="submit" value="Update List" name="action:UpdateBuildIdsList"  />
                <p class="text-danger">@TempData["UpdateBuildIdsListException"]</p>
        </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" name="action:Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KPax/Views/TeamCitySetup/Details.cshtml
@model KPax.DataModels.TeamCitySetup

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TeamCitySetup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Uri)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uri)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Crendential)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Crendential)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdProject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdProject)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KPax/Views/TeamCitySetup/Edit.cshtml
@model KPax.Models.TeamCityViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TeamCity setup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        
        <div class="form-group">
            @Html.LabelFor(m => m.Project, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
               @Html.DropDownListFor(m => m.Project.Id, Model.ProjectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Project.Id)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.URI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BuildId, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.BuildId, Model.BuildIdsList, "Select..", new { @class = "form-control" })
                <input type="submit" value="Update List" name="action:UpdateBuildIdsList" />
                <p class="text-danger">@TempData["UpdateBuildIdsListException"]</p>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" name="action:Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KPax/Views/TeamCitySetup/Index.cshtml
@model IEnumerable<KPax.Models.TeamCityViewModel>

@{
    ViewBag.Title = "TeamCity setup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.URI)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Project)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BuildId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.URI)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Project.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BuildId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new {  id = item.Id  },
            new { onclick = "return confirm('Are you sure you wish to delete this Setup?');" })
        </td>
    </tr>
}

</table>

KPax/Views/TeamCitySetup/Setup.cshtml
@model  KPax.Models.TeamCityViewModel

@{
    ViewBag.Title = "TeamCity setup";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Setup", "TeamCitySetup", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a TeamCity administrator account.</h4>
                <hr />
                @Html.ValidationSummary(true)
                if (TempData["Success"] != null)
                {
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert">&times;</a>
                        <strong>Success!</strong> Data successfully saved.
                    </div>
                }
                <div class="form-group">
                    @Html.LabelFor(m => m.URI, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.URI, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.URI)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", @Autocomplete = "off" })
                        @Html.ValidationMessageFor(m => m.UserName)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @Autocomplete = "off" })
                        @Html.ValidationMessageFor(m => m.Password)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.ProjectId, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.ProjectId, ViewBag.ProjectsList as SelectList, string.Empty)
                        @Html.ValidationMessageFor(m => m.ProjectId)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}